apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: weiyang-eks-cluster
  region: ap-southeast-1

vpc:
  subnets:
      ap-southeast-1a: { id: subnet-029e3eaba4a08cfd9 }
      ap-southeast-1b: { id: subnet-0a079b175239171ae }
      ap-southeast-1c: { id: subnet-024373a5351a4af15 }

nodeGroups:
  - name: weiyang-worker
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 1